#! /usr/bin/env python3

'''
Plot coronavirus data
'''

import os
import sys
import subprocess
import datetime
import csv
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import yaml

def main():
    '''
    Run
    '''

    # Load config
    path = os.path.expanduser('~/.corona')
    with open(f'{path}/corona.yaml') as fhl:
        cfg = yaml.load(fhl)

    # Update data
    if 'pull' not in cfg or cfg['pull']:
        subprocess.check_call(['git', 'pull'],
                              cwd=f"{path}/{cfg['directory']}")

    # Load data
    countries = set(cfg['countries'])
    data = {}
    first = True
    with open(f"{path}/{cfg['directory']}/{cfg['file']}") as fhl:
        for line in csv.reader(fhl):
            if first:
                dates = [datetime.datetime.strptime(day, '%m/%d/%y')
                         for day in line[4:]]
                first = False
            elif line[1] in countries:
                if line[1] in data:
                    data[line[1]] = [int(old) + int(new)
                                     for old, new
                                     in zip(data[line[1]], line[4:])]
                else:
                    data[line[1]] = line[4:]

    # Plot
    fig, axs = plt.subplots()
    axs.xaxis.set_major_locator(mdates.WeekdayLocator())
    axs.xaxis.set_minor_locator(mdates.DayLocator())
    axs.xaxis.set_major_formatter(mdates.DateFormatter(cfg['dateformat']))
    plt.grid(which='major')
    plt.grid(which='minor', linewidth=.5)
    for country in data:
        if 'log' in cfg and cfg['log']:
            axs.semilogy(dates, data[country], label=country)
        else:
            axs.plot(dates, data[country], label=country)
    plt.legend()
    fig.autofmt_xdate()
    plt.savefig(os.path.expanduser(cfg['out']), dpi=cfg['resolution'])


if __name__ == '__main__':
    sys.exit(main())
